task2 ch1
Andrewen99/TestGuru pull request #2
Opened 2021-04-28 19:40 UTC by Andrewen99

Сделаль

2021-04-29 18:23 UTC, VidgarVii requested changes

2021-04-29 18:23 UTC, VidgarVii commented on db/migrate/20210428192355_add_null_constraints.rb
> +class AddNullConstraints < ActiveRecord::Migration[6.1]
не надо добавлять отдельные миграции для изменения полей в одном ПР.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу.
Пример
```
t.string :title, null: false

2021-04-29 18:23 UTC, VidgarVii commented on db/migrate/20210428190224_create_tests.rb
> +      t.timestamps
на этом задании надо еще добавить связи м/у таблицами. 
Так как тест принадлежит определенной категории надо использовать метод references
пример

```
t.references :category, null: false, foreign_key: true
```

2021-04-29 19:34 UTC, Andrewen99 commented on db/migrate/20210428190224_create_tests.rb
> +      t.timestamps
Да,  не увидел это в задании, думал может в след дз будем этим заниматься

2021-04-29 19:34 UTC, Andrewen99 commented on db/migrate/20210428192355_add_null_constraints.rb
> +class AddNullConstraints < ActiveRecord::Migration[6.1]
Понял, поправил

2021-04-30 15:32 UTC, VidgarVii requested changes

2021-04-30 15:32 UTC, VidgarVii commented on db/migrate/20210428190224_create_tests.rb
> +
нужна еще связь с автором теста

2021-04-30 15:32 UTC, VidgarVii commented on db/migrate/20210428191100_create_answers.rb
> +      t.boolean :correct, default: true
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2021-04-30 15:53 UTC, Andrewen99 commented on db/migrate/20210428191100_create_answers.rb
> +      t.boolean :correct, default: true
Хорошо, я думал, что дефолтное значение подразумевает замену null

2021-04-30 15:53 UTC, Andrewen99 commented on db/migrate/20210428190224_create_tests.rb
> +
Добавил

2021-04-30 16:15 UTC, VidgarVii approved these changes

2021-04-30 19:20 UTC, merged